FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
COPY tsconfig.json tsconfig.build.json nest-cli.json prisma.config.ts ./
RUN npm install

COPY entrypoint.dev.sh ./
RUN chmod +x entrypoint.dev.sh

ENTRYPOINT ["sh", "entrypoint.dev.sh"]
